sudo: required
services:
   - docker

before_install:
   - sudo gem install bundler
   - docker build -t werton13/docker-react -f Dockerfile.dev .
script:
#   - docker run werton13/docker-react npm run test -- --coverage
    - docker run -e CI=true werton13/docker-react npm run test  

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "docker-react"
   env: "DockerReact-env"
# files for application in *.zip file a service name in AWSS3
# (scalable storage elasticbeanstalk-RegionName-ID - can be viewed in S3 Storage )
   bucket_name: "elasticbeanstalk-us-east-2-332194135470"
   bucket_path: "docker-react"
on:
   branch: master

access_key_id: "$AWS_ACCESS_KEY"
secret_access_key: "$AWS_SECRET_KEY"
