sudo: required
   services:
      -docker
  
   before_install:
      - docker build -t werton13/docker-react -f Dockerfile.dev .
  
   script:
      - docker run werton13/docker-react npm run test -- --coverage

   
